# Generated by Django 4.2.15 on 2024-08-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.CharField(default="Anuja", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(default="Italian", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="ratings",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
